/**
 * Number-identity invariant.
 *
 * The Button Presser collection is named by Presser numbers. The
 * canonical key for taxonomy joins, listing state, and token display
 * depends on a single invariant:
 *
 *   contract tokenId == OpenSea `nft.identifier` == Presser trait value
 *
 * This module asserts that invariant against a recorded fixture. The
 * fixture is generated by `scripts/probe-number-identity.ts` which
 * queries the OpenSea-backed diagnostic endpoint
 * `/api/v1/diag/number-identity/{tokenId}`.
 *
 * The fixture is checked into source control so the unit test never
 * makes a network call.
 */

export type NumberIdentitySample = {
  requestedTokenId: string;
  identifier: string | null;
  name: string | null;
  presserTraitValue: string | null;
};

export type NumberIdentityFixture = {
  sampledAt: string;
  target: string;
  samples: NumberIdentitySample[];
};

export type NumberIdentityVerdict = {
  /** True when every sample that returned data matches the invariant. */
  identityHolds: boolean;
  /** True when every present Presser trait value equals the tokenId. */
  presserTraitHolds: boolean;
  /** True when every OpenSea identifier equals the requested tokenId. */
  identifierHolds: boolean;
  totalSamples: number;
  matchedSamples: number;
  missingSamples: number;
  divergentSamples: NumberIdentityDivergence[];
};

export type NumberIdentityDivergence = {
  requestedTokenId: string;
  reason: 'identifier-mismatch' | 'presser-mismatch' | 'identifier-missing' | 'presser-missing';
  identifier: string | null;
  presserTraitValue: string | null;
};

/**
 * The Presser trait value occasionally carries a hyphenated range for
 * collection-level filters (e.g. "100 - 999"). Token-level Presser
 * values are single numbers. We accept either form when comparing the
 * trait value to the tokenId.
 */
function traitMatchesTokenId(presserTraitValue: string, requestedTokenId: string): boolean {
  if (presserTraitValue === requestedTokenId) return true;
  const normalized = presserTraitValue.replace(/\s+/g, ' ').trim();
  if (normalized === requestedTokenId) return true;
  const dashMatch = normalized.match(/^(\d+)\s*-\s*(\d+)$/);
  if (dashMatch) {
    const lo = Number(dashMatch[1]);
    const hi = Number(dashMatch[2]);
    const id = Number(requestedTokenId);
    if (Number.isFinite(lo) && Number.isFinite(hi) && Number.isFinite(id)) {
      return id >= lo && id <= hi;
    }
  }
  return false;
}

export function evaluateNumberIdentity(fixture: NumberIdentityFixture): NumberIdentityVerdict {
  let matched = 0;
  let missing = 0;
  const divergent: NumberIdentityDivergence[] = [];

  let identifierHolds = true;
  let presserTraitHolds = true;

  for (const sample of fixture.samples) {
    if (sample.identifier === null && sample.presserTraitValue === null && sample.name === null) {
      missing++;
      continue;
    }
    if (sample.identifier === null) {
      identifierHolds = false;
      divergent.push({
        requestedTokenId: sample.requestedTokenId,
        reason: 'identifier-missing',
        identifier: sample.identifier,
        presserTraitValue: sample.presserTraitValue,
      });
      continue;
    }
    if (sample.identifier !== sample.requestedTokenId) {
      identifierHolds = false;
      divergent.push({
        requestedTokenId: sample.requestedTokenId,
        reason: 'identifier-mismatch',
        identifier: sample.identifier,
        presserTraitValue: sample.presserTraitValue,
      });
      continue;
    }
    if (sample.presserTraitValue === null) {
      presserTraitHolds = false;
      divergent.push({
        requestedTokenId: sample.requestedTokenId,
        reason: 'presser-missing',
        identifier: sample.identifier,
        presserTraitValue: sample.presserTraitValue,
      });
      continue;
    }
    if (!traitMatchesTokenId(sample.presserTraitValue, sample.requestedTokenId)) {
      presserTraitHolds = false;
      divergent.push({
        requestedTokenId: sample.requestedTokenId,
        reason: 'presser-mismatch',
        identifier: sample.identifier,
        presserTraitValue: sample.presserTraitValue,
      });
      continue;
    }
    matched++;
  }

  const identityHolds = identifierHolds && presserTraitHolds && divergent.length === 0;

  return {
    identityHolds,
    presserTraitHolds,
    identifierHolds,
    totalSamples: fixture.samples.length,
    matchedSamples: matched,
    missingSamples: missing,
    divergentSamples: divergent,
  };
}