/**
 * Asserts the number-identity invariant against a recorded fixture.
 * The fixture is generated by `scripts/probe-number-identity.ts` against
 * a server with OPENSEA_API_KEY configured. The fixture is checked into
 * source control so this test never makes a network call.
 *
 * If the test fails, regenerate the fixture and inspect the divergence
 * list before changing the assertion. A divergence usually means either
 * (a) the collection has changed in a way that breaks the invariant, or
 * (b) OpenSea is now returning data we did not account for.
 */

import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  evaluateNumberIdentity,
  type NumberIdentityFixture,
} from './number-identity';

const FIXTURE_PATH = resolve(
  process.cwd(),
  'fixtures/number-identity.json',
);

function loadFixture(): NumberIdentityFixture | null {
  if (!existsSync(FIXTURE_PATH)) return null;
  const raw = readFileSync(FIXTURE_PATH, 'utf8');
  return JSON.parse(raw) as NumberIdentityFixture;
}

describe('number-identity invariant', () => {
  const fixture = loadFixture();

  it('has a checked-in fixture', () => {
    expect(fixture).not.toBeNull();
    if (!fixture) return;
    expect(Array.isArray(fixture.samples)).toBe(true);
    expect(fixture.samples.length).toBeGreaterThan(0);
  });

  it('covers the requested sample buckets', () => {
    if (!fixture) return;
    const ids = new Set(fixture.samples.map((s) => s.requestedTokenId));
    for (const expected of ['1', '100', '966', '628', '870', '507', '756', '635']) {
      expect(ids.has(expected)).toBe(true);
    }
    // Boundary samples.
    for (const boundary of ['9', '10', '99', '100', '999', '1000', '9999', '10000']) {
      expect(ids.has(boundary)).toBe(true);
    }
  });

  it('OpenSea identifier matches the requested tokenId for every present sample', () => {
    if (!fixture) return;
    const verdict = evaluateNumberIdentity(fixture);
    expect(verdict.identifierHolds).toBe(true);
    if (!verdict.identifierHolds) {
      // Surface the first divergence for debugging.
      // eslint-disable-next-line no-console
      console.error(JSON.stringify(verdict.divergentSamples.slice(0, 5), null, 2));
    }
  });

  it('Presser trait value matches the requested tokenId for every present sample', () => {
    if (!fixture) return;
    const verdict = evaluateNumberIdentity(fixture);
    expect(verdict.presserTraitHolds).toBe(true);
  });

  it('the combined invariant holds across the sample', () => {
    if (!fixture) return;
    const verdict = evaluateNumberIdentity(fixture);
    expect(verdict.identityHolds).toBe(true);
  });
});